### ISSUE TITLE
Missing operators: bitwise, unary, multiplicative, op=

### ISSUE THREAD

**Issue by martinmoene** [anthonywilliams/strong_typedef#1]
I didn't spot the following operators:
- bitwise: ~ & ¦ ^ &lt;&lt; >>
- multiplicative: \* / %
- unary+, unary-
- op= counterparts

Are these yet to be added?
Does `op=` fit in this approach?  If not, what about "do as the ints do"?

**Comment by anthonywilliams** [comment]
All these are on the list to be added (if not already added), I've just not needed them as part of the generic framework before, I've always either used `enum class` for bitfields, (as per my blog post: https://www.justsoftwaresolutions.co.uk/cplusplus/using-enum-classes-as-bitfields.html ), or written a full type that provided the other operations.

**Comment by martinmoene** [comment]
Wonderful!
